### ISSUE TITLE
How to remove brown filter in background image

### ISSUE THREAD

**Issue by Happysmilesinc** [StartBootstrap/startbootstrap-business-casual#50]
How to remove the brown filter shadow from the background image?

**Comment by ntharani51** [comment]
Did you manage to solve this problem?

**Comment by davidtmiller** [comment]
There is a linear gradient applied to the background image property on the body element. You can change this in the CSS or in the SCSS and recompile. Look for `background-image: linear-gradient(rgba(47, 23, 15, 0.65), rgba(47, 23, 15, 0.65)), url('../img/bg.jpg');` and change it to `background-image: url('../img/bg.jpg');` or change the values in the background gradient. Hopefully this helps!
