### ISSUE TITLE
Suggested tweak to .cta-inner:before styling to fix unclickable hyperlinks on store.html container

### ISSUE THREAD

**Issue by freakwriter** [StartBootstrap/startbootstrap-business-casual#52]
I'm using this template for a website, and repurposed the store.html layout for a contact us page, since I liked the layout.

The .cta-inner:before styling that's doing that lovely border causes some z-index issues if you have hyperlinks in that content. I added a negative z-index value to the CSS there to fix this after researching it a bit, and that fixed it right up. Not sure if that's a change y'all would like to make in the template, but it might be helpful for other folks!

**Comment by adriannelson** [comment]
Thanks, freakwriter, helped me out

**Comment by freakwriter** [comment]
@adriannelson glad it helped!

**Comment by duleorlovic** [comment]
Yea, z-index is a solution.
```
.cta-inner:before {
  z-index: -1;
}
```
@freakwriter  can you create a pull request ? If not, I would create PR so future devs can click on links :)

**Comment by freakwriter** [comment]
@duleorlovic PR is here: https://github.com/BlackrockDigital/startbootstrap-business-casual/pull/65

**Comment by davidtmiller** [comment]
I worked this into the SCSS and recompiled. The pull request just targets the minified compiled CSS so I'll be closing that, but the change will be implemented and recompiled. Thanks!
